server:
  port: 8080


spring:
  #security:
    #user:
    #  name: zwq
     # password: 123456
  application:
    name: cloud-payment-service  #名字一般不要改变 就是注册中心的名称
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: root

